clc; clear;

StartDirectory = pwd;

addpath(fullfile(StartDirectory, 'SubFun'))

SubjectList = [...
%     '02';...
%     '03';...
%     '04';...
%     '06';...
%     '07';...
%     '08';...
%     '09';...
%     '11';...
%     '12';...
%     '13';...
%     '14';...
%     '15';...
    '16'
    ];

 for SubjInd = 1 %size(SubjectList,1)
     
     SubjID = SubjectList(SubjInd,:);
     
     SubjectFolder = fullfile(StartDirectory, 'Subjects_Data', ['Subject_' SubjID]);
     
     fprintf('\nAnalysing subject %s\n', SubjID)
         
     AnalysisFolder = fullfile(SubjectFolder, 'Transfer');
     cd(AnalysisFolder)
     BetaFiles = dir('rbeta*.nii');
     for iBeta = 1:numel(BetaFiles)
         hdr = spm_vol(BetaFiles(iBeta).name);
         vol = spm_read_vols(hdr);
         vol(isnan(vol))=0;
         spm_write_vol(hdr,vol);
         hdr=[]; vol=[];
     end
     
 end
