clear; clc;

StartFolder = pwd;

SubjectList = [...
    '02';...
    '03';...
    '04';...
    '06';...
    '07';...
    '08';...
    '09';...
    '11';...
    '12';...
    '13';...
    '14';...
    '15';...
    '16'
    ];


for SubjInd = 1:size(SubjectList,1)
    
    SubjID = SubjectList(SubjInd,:);
    
    SubjectFolder = fullfile(StartFolder, 'Subjects_Data', ['Subject_' SubjID]);
    
    SubXP = sprintf('exp-00%02.0f', 0+SubjInd-1);
    
    fprintf(['\n\nProcessing subject : ' SubjID '\n'])
    
    
    fprintf('\n Transferring files\n')
    
    cd(fullfile(SubjectFolder, 'Structural', 'CBS', 'Layering'))
    
    copyfile( ...
        fullfile(pwd, SubXP, [SubXP '-B'], 'VolumetricLayering', 'T1*labels*'), pwd);
    movefile(['T1_' SubjID '_thresh_clone_transform_strip_clone_transform_bound_mems_cr_gm__labels.nii.gz'], ...
        'T1_10_Layers.nii.gz');
    
    copyfile( ...
        fullfile(pwd, SubXP, [SubXP '-C'], 'VolumetricLayering', 'T1*labels*'), pwd);
    movefile(['T1_' SubjID '_thresh_clone_transform_strip_clone_transform_bound_mems_cr_gm__labels.nii.gz'], ...
        'T1_04_Layers.nii.gz');
    
    copyfile( ...
        fullfile(pwd, SubXP, [SubXP '-D'], 'VolumetricLayering', 'T1*labels*'), pwd);
    movefile(['T1_' SubjID '_thresh_clone_transform_strip_clone_transform_bound_mems_cr_gm__labels.nii.gz'], ...
        'T1_06_Layers.nii.gz');
    
    system('gunzip -f *.gz');
    
end