clear; clc;

% StartDirectory = fullfile(pwd, '..', '..');
StartDirectory = '/media/rxg243/BackUp2/AV_Integration_7T_2';

SubjectList = [...
    '02';...
    '03';...
    '04';...
    '06';...
    '07';...
    '08';...
    '09';...
    '11';...
    '12';...
    '13';...
    '14';...
    '15';...
    '16'
    ];


for SubjInd = 1:size(SubjectList,1)
    
    SubjID = SubjectList(SubjInd,:)
    
    SubjectFolder = fullfile(StartDirectory, 'Subjects_Data', ['Subject_' SubjID]);
    
%     mkdir(fullfile(SubjectFolder, 'Transfer'))
%     mkdir(fullfile(SubjectFolder, 'Transfer2'))
    
%     copyfile(fullfile(SubjectFolder, 'Nifti', 'NoMoCo', '01', 'mean*.nii'), fullfile(SubjectFolder, 'Transfer'))
%     copyfile(fullfile(SubjectFolder, 'mean*.nii'), fullfile(SubjectFolder, 'Transfer'))
%     copyfile(fullfile(SubjectFolder, 'FFX_NoSmooth', 'con*.nii'), fullfile(SubjectFolder, 'Transfer')) 

%     copyfile(fullfile(SubjectFolder, 'Nifti', 'NoMoCo', '01', 'meanuS*.nii'), fullfile(SubjectFolder, 'Transfer2'))
%     copyfile(fullfile(SubjectFolder, 'Nifti', 'NoMoCo', '01', 'meanu2S*.nii'), fullfile(SubjectFolder, 'Transfer2'))
    
    copyfile(fullfile(SubjectFolder, 'Transfer', 'ReorientMatrix_*.mat'), fullfile(SubjectFolder, 'Transfer2'))
    
    
%     load(fullfile(SubjectFolder, 'FFX_Block', 'SPM.mat'))
%     
%     BetaNames = char(SPM.xX.name');
%     
%     BetaOfInterest = ~any([BetaNames(:,9)=='T' BetaNames(:,7)=='R' BetaNames(:,7)=='c' ...
%         strcmp(cellstr(BetaNames(:,end-1:end)), '2)') ...
%         strcmp(cellstr(BetaNames(:,end-2:end-1)), '2)') ...
%         strcmp(cellstr(BetaNames(:,end-3:end-2)), '2)') ...
%         strcmp(cellstr(BetaNames(:,end-4:end-3)), '2)')], ...
%         2);
%     
%     BetaOfInterest = find(BetaOfInterest);
%     
%     for i=1:length(BetaOfInterest)
%         copyfile(fullfile(SubjectFolder, 'FFX_Block',  sprintf('beta_%04d.nii', BetaOfInterest(i))), ...
%             fullfile(SubjectFolder, 'Transfer'))
%     end
%     
%     copyfile(fullfile(SubjectFolder, 'FFX_Block', 'mask.nii' ), ...
%             fullfile(SubjectFolder, 'Transfer'))

end