clear; clc

%  Folders definitions
% RootFolder = fullfile(pwd, '..', '..');
RootFolder = '/media/rxg243/BackUp2/AV_Integration_7T_2';

SubjectList = [...
    '02';...
    '03';...
    '04';...
    '06';...
    '07';...
    '08';...
    '09';...
    '11';...
    '12';...
    '13';...
    '14';...
    '15';...
    '16'
    ];


FoldersNames = {...
    1:4;...
    1:4;...
    1:4;...
    1:2;...
    1:4;...
    1:4;...
    1:4;...
    1:4;...
    1:4;...
    1:4;...
    1:2;...
    1:4;...
    1:4;...
    };

for SubjInd = 2:size(SubjectList,1)
    
    SubjID = [];
    
    SubjID = SubjectList(SubjInd,:)
    
    SubjectFolder = fullfile(RootFolder, 'Subjects_Data', ['Subject_' SubjID]);
    
    NiftiSourceFolder = fullfile(SubjectFolder, 'Nifti', 'NoMoCo');
    
    NbRuns = length( FoldersNames{SubjInd});
    
    matlabbatch = {};
    
    for RunInd=1:NbRuns
        
        RunInd
        
        cd(fullfile(NiftiSourceFolder, sprintf('%2.2d', FoldersNames{SubjInd}(RunInd))))
        TEMP = dir('URS1*iPAT4_6_8_48sli_TE25_0p75_Te25.nii');
        Hdr = spm_vol(TEMP.name);
        Vol = spm_read_vols(Hdr);
        Mean = mean(Vol,4); 
        Hdr = Hdr(1);
        Hdr.fname = ['mean_session_' num2str(RunInd) '.nii'];
        spm_write_vol(Hdr,Mean)

        clear Hdr Mean Vol TEMP
    end
    
    cd (RootFolder)

    
end