clear; clc;

% StartDirectory = fullfile(pwd, '..','..', '..');
StartDirectory = '/media/rxg243/BackUp2/AV_Integration_7T_2';

SubjectList = [...
    '02';...
    '03';...
    '04';...
    '06';...
    '07';...
    '08';...
    '09';...
    '11';...
    '12';...
    '13';...
    '14';...
    '15';...
    '16'
    ];

FoldersNames = {...
    1:4;...
    1:4;...
    1:4;...
    1:2;...
    1:4;...
    1:4;...
    1:4;...
    1:4;...
    1:4;...
    1:4;...
    1:2;...
    1:4;...
    1:4;...
    };

DateFormat = 'yyyy_mm_dd_HH_MM';

for SubjInd = 11:size(SubjectList,1)

    SubjID = SubjectList(SubjInd,:);
    
    SubjectFolder = fullfile(StartDirectory, 'Subjects_Data', ['Subject_' SubjID]);
    
    NiftiSourceFolder = fullfile(SubjectFolder, 'Nifti', 'NoMoCo');

    NbRuns = length(FoldersNames{SubjInd});
    
    matlabbatch = {};
    Files2Reorient = {};
    

    for RunInd=1:NbRuns
        
        cd(fullfile(NiftiSourceFolder, sprintf('%2.2d', FoldersNames{SubjInd}(RunInd))))
        
        if RunInd==1
            MeanFile = dir('meanu2*.nii');
            Files2Reorient{1,1} = fullfile(pwd, [MeanFile(1).name ',1']); 
        end
       
        TEMP = dir('u2S*.nii');
        TEMP = spm_vol(TEMP.name);
        
        for i=1:length(TEMP)
            Files2Reorient{end+1,1} = [fullfile(pwd,TEMP(i).fname) ,',', num2str(i)]; %#ok<*SAGROW>
        end

    end

    cd(fullfile(NiftiSourceFolder, sprintf('%2.2d', FoldersNames{SubjInd}(1))))
    ReorientFiles = dir('mean*_reorient.mat');
    load(fullfile(pwd, ReorientFiles.name))
    
    matlabbatch{1}.spm.util.reorient.srcfiles = Files2Reorient;
    matlabbatch{1}.spm.util.reorient.transform.transM = M;
    matlabbatch{1}.spm.util.reorient.prefix = '';
    
    
    save (strcat('ReorientRealignUnwarp2EPI_Subject_', SubjID, '_', datestr(now, DateFormat), '_jobs.mat'));
    
    spm_jobman('run', matlabbatch)

end